
### CRUD endonsumers
### GET all endconsumers
GET http://localhost:8080/backend/api/endConsumers

### GET endconsumer by id
GET http://localhost:8080/backend/api/endConsumers/endConsumer2

### POST endconsumer
POST http://localhost:8080/backend/api/endConsumers
Content-Type: application/json

  {
    "username": "endConsumer3",
    "password": "endConsumer3",
    "name": "endConsumer3",
    "email": "endConsumer3",
    "role": "endConsumer"
    }

### PUT endconsumer
PUT http://localhost:8080/backend/api/endConsumers/endConsumer3
Content-Type: application/json

{
  "username": "endConsumer3",
  "password": "endConsumer3",
  "name": "endConsumer33333",
  "email": "endConsumer3",
  "role": "endConsumer"
}

### DELETE endconsumer
DELETE http://localhost:8080/backend/api/endconsumers/endConsumer3

### CRUD manufacturers
### GET all manufacturers
GET http://localhost:8080/backend/api/manufacturers

### GET manufacturer by id
GET http://localhost:8080/backend/api/manufacturers/manufacturer2/products

### POST manufacturer
POST http://localhost:8080/backend/api/manufacturers
Content-Type: application/json

{
  "username": "manufacturer3",
  "password": "manufacturer3",
  "name": "manufacturer3",
  "email": "manufacturer3@manufacturer3.pt",
  "role": "manufacturer"
}

### PUT manufacturer
PUT http://localhost:8080/backend/api/manufacturers/manufacturer3
Content-Type: application/json

{
  "username": "manufacturer3",
  "password": "manufacturer3",
  "name": "manufacturer333333",
  "email": "manufacturer3@manufacturer3.pt",
  "role": "manufacturer"
}

### DELETE manufacturer
DELETE http://localhost:8080/backend/api/manufacturers/manufacturer3

### CRUD logisticsOperators
### GET all logisticsOperators
GET http://localhost:8080/backend/api/logisticsOperators

### GET logisticsOperator by id
GET http://localhost:8080/backend/api/logisticsOperators/logisticsOperator1



### Get all products
GET http://localhost:8080/backend/api/products

### Get product by id
GET http://localhost:8080/backend/api/products/1

### Post product
POST http://localhost:8080/backend/api/products
Content-Type: application/json

{
  "name": "product3",
  "stock": 10,
  "manufacturerUsername": "manufacturer1"
}

### Put product
PUT http://localhost:8080/backend/api/products/1
Content-Type: application/json

{
  "id"  : 1,
  "name": "product_teste_again",
  "stock": 1,
  "manufacturerUsername": "manufacturer1"
}

### Delete product
DELETE http://localhost:8080/backend/api/products/11


### CRUD package
### GET all packages
GET http://localhost:8080/backend/api/packages

### Post package
POST http://localhost:8080/backend/api/packages
Content-Type: application/json

{
  "id"  : 123,
  "packagingType": "SECONDARY",
  "packagingMaterial": "test_material"
}

### Put package
PUT http://localhost:8080/backend/api/packages/111
Content-Type: application/json

{
  "id": 111,
  "packagingType": "THIRD",
  "packagingMaterial": "Plastico"
}

### Delete package
DELETE http://localhost:8080/backend/api/packages/123
