
### CRUD endonsumers
### GET all endconsumers
GET http://localhost:8080/backend/api/endConsumers

### GET endconsumer by id
GET http://localhost:8080/backend/api/endConsumers/endConsumer2

### POST endconsumer
POST http://localhost:8080/backend/api/endConsumers
Content-Type: application/json

  {
    "username": "endConsumer3",
    "password": "endConsumer3",
    "name": "endConsumer3",
    "email": "endConsumer3",
    "role": "endConsumer"
    }

### PUT endconsumer
PUT http://localhost:8080/backend/api/endConsumers/endConsumer3
Content-Type: application/json

{
  "username": "endConsumer3",
  "password": "endConsumer3",
  "name": "endConsumer33333",
  "email": "endConsumer3",
  "role": "endConsumer"
}

### DELETE endconsumer
DELETE http://localhost:8080/backend/api/endconsumers/endConsumer3

### request JWT token
POST http://localhost:8080/backend/api/auth/login
Content-Type: application/json
Accept: application/json

    {
    "username": "manufacturer2",
    "password": "manufacturer2"
    }
### CRUD manufacturers
### GET all manufacturers
GET http://localhost:8080/backend/api/manufacturers
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtYW51ZmFjdHVyZXIyIiwiaWF0IjoxNzAzNzY3MzM2LCJleHAiOjE3MDM3NzA5MzZ9.IeKWFtg58n9gxvRkMvHe4uK-okvzFDclVump9zTvLK0rMfO6vjao5C1-Bve2LZfF

### GET manufacturer by id
GET http://localhost:8080/backend/api/manufacturers/manufacturer2

### POST manufacturer
POST http://localhost:8080/backend/api/manufacturers
Content-Type: application/json

{
  "username": "manufacturer3",
  "password": "manufacturer3",
  "name": "manufacturer3",
  "email": "manufacturer3@manufacturer3.pt",
  "role": "manufacturer"
}

### PUT manufacturer
PUT http://localhost:8080/backend/api/manufacturers/manufacturer3
Content-Type: application/json

{
  "username": "manufacturer3",
  "password": "manufacturer3",
  "name": "manufacturer333333",
  "email": "manufacturer3@manufacturer3.pt",
  "role": "manufacturer"
}

### get all products from manufacturer
GET http://localhost:8080/backend/api/manufacturers/manufacturer1/products

### DELETE manufacturer
DELETE http://localhost:8080/backend/api/manufacturers/manufacturer3

### CRUD logisticsOperators
### GET all logisticsOperators
GET http://localhost:8080/backend/api/logisticsOperators

### GET logisticsOperator by id
GET http://localhost:8080/backend/api/logisticsOperators/logisticsOperator1

### Get product by id
GET http://localhost:8080/backend/api/products

### Post product
POST http://localhost:8080/backend/api/products
Content-Type: application/json

{
  "name": "product3",
  "stock": 3,
  "manufacturerUsername": "manufacturer1",
  "image": "imagem"
}

### set product package
PUT http://localhost:8080/backend/api/products/2/package/2

### Put product
PUT http://localhost:8080/backend/api/products/1
Content-Type: application/json

{
  "name": "product_3",
  "stock": 1,
  "image": "imagem3",
  "manufacturerUsername": "manufacturer1"
}

### Delete product
DELETE http://localhost:8080/backend/api/products/2

### get all units from product
GET http://localhost:8080/backend/api/products/1/unitProducts


## order
### Get all orders
GET http://localhost:8080/backend/api/orders

### Get order by id
GET http://localhost:8080/backend/api/orders/1

### Get items of a order
GET http://localhost:8080/backend/api/orders/1/items

### CRUD package
### GET all packages
GET http://localhost:8080/backend/api/packages

### GET all packages by id
GET http://localhost:8080/backend/api/packages/2

### GET all package sensors
GET http://localhost:8080/backend/api/packages/4/sensors

### Post package
POST http://localhost:8080/backend/api/packages
Content-Type: application/json

{
  "id"  : 3,
  "packagingType": "SECONDARY",
  "packagingMaterial": "test_material"
}

### Delete sensor from package
DELETE http://localhost:8080/backend/api/packages/2/sensor/2

### Put package
PUT http://localhost:8080/backend/api/packages/111
Content-Type: application/json

{
  "id": 111,
  "packagingType": "THIRD",
  "packagingMaterial": "Plastico"
}

### Delete package
DELETE http://localhost:8080/backend/api/packages/123

### authentication
### login
POST http://localhost:8080/backend/api/auth/login
Content-Type: application/json

{
  "username": "manufacturer1",
  "password": "manufacturer1"
}

### get all orders with order items
GET http://localhost:8080/backend/api/endConsumers/endConsumer1/orders

### post order with order items by endconsumer
POST http://localhost:8080/backend/api/endConsumers/endConsumer2/orders
Content-Type: application/json

{
  "status": "WAITING_PAYMENT",
  "orderItems": [
    {
      "quantity": 1,
      "productId": "1"
    }
  ]
}

###

GET http://localhost:8080/backend/api/orders/1

## products
### Get all products
GET http://localhost:8080/backend/api/products/2


### get unitProducts
GET http://localhost:8080/backend/api/orders

### get all units from product
GET http://localhost:8080/backend/api/products/1/unitProducts

### get all packages from product
GET http://localhost:8080/backend/api/packageProducts/type/PRIMARY

### create package
PUT http://localhost:8080/backend/api/packageProducts/1
Content-Type: application/json

{
  "packagingType": 1,
  "packagingMaterial": "test_material"
}

### get all packages from product
GET http://localhost:8080/backend/api/unitProducts/1

### get all sensors
GET http://localhost:8080/backend/api/sensors

### add a new sensor
POST http://localhost:8080/backend/api/sensors
Content-Type: application/json

{
  "source": "test_source",
  "type": "TEMPERATURE",
  "unit": "CELSIUS",
  "max": 100,
  "min": 0

}

### get all packages from product
GET http://localhost:8080/backend/api/products/1/sensorsNotAttribute

### get all packages from product
GET http://localhost:8080/backend/api/unitProducts


### get all packages from product
GET http://localhost:8080/backend/api/unitProducts/4
###
PUT http://localhost:8080/backend/api/unitProducts/4/addSensor/1

### get all packages from product
GET http://localhost:8080/backend/api/manufacturers/manufacturer1/products

### get all packages from product
PUT http://localhost:8080/backend/api/products/2/unitProduct

### get all packages from product
PUT http://localhost:8080/backend/api/products/1
Content-Type: application/json

{
  "name": "product_3_ddd",
  "stock": 1,
  "image": "imagem3",
  "packageProductId": 1
}

### get all packages from product
PUT http://localhost:8080/backend/api/logisticsOperators/logisticsOperator1/order/1/package/2

###
GET http://localhost:8080/backend/api/orders/1